nombre = input("Ingrese su Nombre: ")
apel = input("Ingrese su Apellido: ")
sec = input("Ingrese su Sección: ")
sede = input("Ingrese su Sede: ")
print("-----------------------------")
print("Información Ingresada:")
print("Nombre:",nombre)
print("Apellido:",apel)
print("Sección:",sec)
print("Sede:",sede)
